
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - '*'
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformconfigurations
  verbs:
  - '*'
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformconfigurations/status
  verbs:
  - '*'
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformplans
  verbs:
  - '*'
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformplans/status
  verbs:
  - '*'
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformstates
  verbs:
  - '*'
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformstates/status
  verbs:
  - '*'
