
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kubeterra
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/logs
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.kubeterra.io
  resources:
  - terraformstates/status
  verbs:
  - get
  - patch
  - update
