apiVersion: core.kubeterra.io/v1beta1
kind: TerraformResource
metadata:
  labels:
    setup: sample
  name: terraform-server-sample
spec:
  type: hcloud_server
  parameters:
    name: kubeterra-node1
    image: debian-9
    server_type: cx11
