apiVersion: terraform.kubeterra.io/v1alpha1
kind: TerraformConfiguration
metadata:
  name: sample1
  namespace: kubeterra-system
spec:
  autoApprove: true
  repeatEvery: 10m
  configuration: |
    terraform {
      backend "http" {
        address        = "http://localhost:8081/"
        lock_address   = "http://localhost:8081/"
        unlock_address = "http://localhost:8081/"
      }
    }
    resource "random_id" "server" {
      byte_length = 4
    }
