apiVersion: terraform.kubeterra.io/v1alpha1
kind: TerraformConfiguration
metadata:
  name: sample1
  namespace: kubeterra-system
spec:
  autoApprove: true
  configuration: |
    resource "random_id" "server" {
      byte_length = 4
    }
