apiVersion: terraform.kubeterra.io/v1alpha1
kind: TerraformConfiguration
metadata:
  name: hetzner-sample
spec:
  template:
    metadata:
      labels:
        trigger: me

    volumes:
    - name: sshsecrets
      secret:
        secretName: mysecret

    volumeMounts:
    - mountPath: /secrets
      name: sshsecrets

    serviceAccountName: "some-custom-sa"

  autoApprove: true

  values: |
    cluster_name        = "kubeterra-test"
    datacenter          = "nbg1"
    ssh_public_key_file = "/secrets/project-ssh-key.pub"

  configuration: |
    terraform {
      required_version = ">= 0.12"
    }

    variable "cluster_name" {
      description = "prefix for cloud resources"
    }

    variable "server_type" {
      default = "cx21"
    }

    variable "image" {
      default = "ubuntu-18.04"
    }

    variable "datacenter" {
      default = "fsn1"
    }

    variable "ssh_public_key_file" {
      description = "SSH public key file"
      default     = "~/.ssh/id_rsa.pub"
    }

    variable "ssh_port" {
      description = "SSH port to be used to provision instances"
      default     = 22
    }

    variable "ssh_username" {
      description = "SSH user, used only in output"
      default     = "root"
    }

    provider "hcloud" {}

    resource "hcloud_ssh_key" "kubeterra" {
      name       = "kubeterra-${var.cluster_name}"
      public_key = file(var.ssh_public_key_file)
    }

    resource "hcloud_server" "kubeterra_test" {
      count       = 1
      name        = "${var.cluster_name}-control-plane-${count.index + 1}"
      server_type = var.server_type
      image       = var.image
      location    = var.datacenter

      ssh_keys = [
        hcloud_ssh_key.kubeterra.id,
      ]
    }

    output "kubeterra_hosts" {
      description = "endpoints to SSH to"
      value = {
        control_plane = {
          cluster_name         = var.cluster_name
          public_address       = hcloud_server.kubeterra_test.*.ipv4_address
          ssh_port             = var.ssh_port
          ssh_user             = var.ssh_username
        }
      }
    }
