---
apiVersion: v1
kind: Secret
metadata:
  name: hetzner-credentials
  namespace: kubeterra-system
type: Opaque
stringData:
  HCLOUD_TOKEN: <REPLACE>

---
apiVersion: v1
kind: Secret
metadata:
  name: hetzner-secrets
  namespace: kubeterra-system
type: Opaque
stringData:
  "id_rsa": "<REPLACE>"
  "id_rsa.pub": "<REPLACE>"
